---
# tasks file for binutils

- name: install required packages
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - gcc-gfortran
    - gcc-c++

- name: check if already installed
  stat: path={{ binutils_prefix }}/lib
  register: binutils_lib_dir
  changed_when: binutils_lib_dir.stat.exists == False

- include: install.yml
  when: binutils_lib_dir.stat.exists == False

- name: clean downloaded file
  file: path={{ item }} state=absent
  with_items:
    - /tmp/binutils-{{ binutils_version }}
    - /tmp/binutils-{{ binutils_version }}.tar.gz
